### ISSUE TITLE
什么时候开源dagger-dpo的代码？

### ISSUE THREAD

**Issue by aplmikex** [stevenyangyj/Emma-Alfworld#3]
你好，我非常关注这篇论文，它是多模态大模型从认知走向决策的一个比较有探索意义的科研项目。我很想亲自实验这个算法，害怕自己实现的dagger-dpo存在问题。请问什么时候能开源dagger-dpo算法呢，如果完整代码的开源有困难的话，我也希望能有机会尽早看到dagger-dpo算法核心代码，非常感谢你的贡献。

**Comment by stevenyangyj** [comment]
我最近确实抽不出时间重构之前的代码，如果您着急的话，我可以先上传一个论文版本的DAGGER-DPO供参考，只是可能没办法直接运行。

**Comment by stevenyangyj** [comment]
> 你好，我非常关注这篇论文，它是多模态大模型从认知走向决策的一个比较有探索意义的科研项目。我很想亲自实验这个算法，害怕自己实现的dagger-dpo存在问题。请问什么时候能开源dagger-dpo算法呢，如果完整代码的开源有困难的话，我也希望能有机会尽早看到dagger-dpo算法核心代码，非常感谢你的贡献。

Please refer to this [portion](https://github.com/stevenyangyj/Emma-Alfworld/blob/main/LAVIS/dagger_server.py#L390) of the dagger_server.py.

**Comment by aplmikex** [comment]
> > 你好，我非常关注这篇论文，它是多模态大模型从认知走向决策的一个比较有探索意义的科研项目。我很想亲自实验这个算法，害怕自己实现的dagger-dpo存在问题。请问什么时候能开源dagger-dpo算法呢，如果完整代码的开源有困难的话，我也希望能有机会尽早看到dagger-dpo算法核心代码，非常感谢你的贡献。
> 
> Please refer to this [portion](https://github.com/stevenyangyj/Emma-Alfworld/blob/main/LAVIS/dagger_server.py#L390) of the dagger_server.py.

非常感谢你的贡献，我会仔细读并复现的。

**Comment by aplmikex** [comment]
> > 你好，我非常关注这篇论文，它是多模态大模型从认知走向决策的一个比较有探索意义的科研项目。我很想亲自实验这个算法，害怕自己实现的dagger-dpo存在问题。请问什么时候能开源dagger-dpo算法呢，如果完整代码的开源有困难的话，我也希望能有机会尽早看到dagger-dpo算法核心代码，非常感谢你的贡献。
> 
> Please refer to this [portion](https://github.com/stevenyangyj/Emma-Alfworld/blob/main/LAVIS/dagger_server.py#L390) of the dagger_server.py.

你好，你的openai的api key公开出来了

**Comment by stevenyangyj** [comment]
谢谢提醒 没关系 这是一个过期的key
