### ISSUE TITLE
About code release plan

### ISSUE THREAD

**Issue by eeaurora** [stevenyangyj/Emma-Alfworld#5]
Thank you for your great work about LLM in agent. I would like to know when you will release all of the code  (include implementation and evaluation code)?

Thank you.

**Comment by stevenyangyj** [comment]
Thanks so much for your interest! Actually, I have released the implementation of the agent's architecture (see [this](https://github.com/stevenyangyj/Emma-Alfworld/blob/main/LAVIS/lavis/models/blip2_models/blip2_emma.py)) and training and evaluation code for DAgger + DPO (see [this](https://github.com/stevenyangyj/Emma-Alfworld/blob/main/LAVIS/dagger_server.py)). Currently, the training and evaluation code is highly coupled to the internal developing environment adopted by JD Explore Academy, and I have no time and enough computational resources (The cost of GPU and OpenAI API) to refactor the code for general deployment. If you would like to reproduce the results shown in the paper, you need to install the ALFWorld simulator by yourself and adapt the code to YOUR OWN developing environment. 

I'm willing to provide the necessary help.
