### ISSUE TITLE
Request for BLIP_EMMA Configuration Files

### ISSUE THREAD

**Issue by ejxnxn** [stevenyangyj/Emma-Alfworld#6]
I appreciate your outstanding work on embodied agents. However, I noticed that the configuration files for BLIP_EMMA are not currently available. Could you please let me know when you plan to provide these files?

Thank you for your assistance.

**Comment by stevenyangyj** [comment]
oh, I forgot to upload some important configs for inference and finetuning, I will make them available tonight.

**Comment by ejxnxn** [comment]
Thanks for your quick reply! It seems that a few files might also be missing. If it’s convenient for you, could you please provide the generate_reflections and post_processing files as well?
 
Thank you very much for your assistance!

**Comment by stevenyangyj** [comment]
I hope you can find all the things you need within the current commit.
