### ISSUE TITLE
EMMA评估问题

### ISSUE THREAD

**Issue by shengli98** [stevenyangyj/Emma-Alfworld#8]
您好，我读了您的论文，在huggingface下载Alfworld数据集进行微调instructblip之后，里面只有训练用的数据集，不知道怎么进行下一步对模型的评估，请问您是用的微调instructblip的数据集还是用的其他的数据集？您能提供评估用的数据集吗？

**Comment by stevenyangyj** [comment]
Hello, there are no specific datasets for evaluation; we evaluate the trained model in an interactive environment. If you are interested in evaluating your models in a static dataset (while I do not encourage this as the caused problem of distribution shift), you can check our [another work](https://www.ijcai.org/proceedings/2024/0015.pdf).
